version: '3'
services:
  wp:
    volumes:
      - "app:/var/www/html/web/wp/wp-content"
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - "db:/var/lib/mysql"

volumes:
  app:
  db:

